/* ================================================================
   CoachData Content Desk — Seed Data
   Categories (pillars), idea cards, formula hooks, content series.
================================================================ */

export const SEED_CATS = [
  { id: "cat-engine",  name: "Content Engine",     hue: 152 },
  { id: "cat-site",    name: "Website Rebuild",     hue: 205 },
  { id: "cat-sops",    name: "SOPs & Onboarding",   hue: 36  },
  { id: "cat-clients", name: "Client Delivery",      hue: 272 },
];

export const SEED = [
  {
    id: "c-001", cat: "cat-engine", ref: "AGD-01",
    title: "Film Agency Diaries week one",
    status: "Writing",
    script: "Week one of running a content agency solo. Here's what actually happened.",
    notes: "Four things this week: 250 outreach messages, two podcasts, two proposals, five pieces of content.",
    scenes: ["Intro hook: desk chaos", "Outreach board screen", "Recording setup", "Results reveal"],
    priority: "High",
    format: "Reel",
    platform: "Instagram",
    tags: ["agency", "bts", "weekly"],
  },
  {
    id: "c-002", cat: "cat-engine", ref: "AGD-02",
    title: "Cut the CEO Decisions episode",
    status: "Editing",
    script: "The €1,500 a month retainer decision. I almost said no. Here's why I didn't.",
    notes: "Keep the pause before the answer. That's the hook.",
    scenes: ["The call moment", "The thinking pause", "The decision", "The result"],
    priority: "Normal",
    format: "Reel",
    platform: "Instagram",
    tags: ["decisions", "business"],
  },
  {
    id: "c-003", cat: "cat-engine", ref: "AGD-03",
    title: "Write the evergreen funnel breakdown",
    status: "Ideas",
    script: "Comment EVERGREEN and I'll send you the exact funnel that runs on autopilot.",
    notes: "Promised to anyone who comments EVERGREEN. Needs to exist before that post goes live.",
    scenes: ["The problem", "The funnel steps", "The result", "CTA"],
    priority: "High",
    format: "Carousel",
    platform: "Instagram",
    tags: ["evergreen", "funnel", "lead-magnet"],
  },
  {
    id: "c-004", cat: "cat-sops", ref: "SOP-01",
    title: "Build the scale checklist",
    status: "Ideas",
    script: "Comment SYSTEMS and I'll send you the checklist that lets me run this without being everywhere.",
    notes: "The SYSTEMS keyword sends people here. Cannot post that script until this is real.",
    scenes: ["The problem (overwhelm)", "The 5 systems", "The checklist reveal", "CTA"],
    priority: "High",
    format: "Carousel",
    platform: "Instagram",
    tags: ["systems", "scale", "checklist"],
  },
  {
    id: "c-005", cat: "cat-sops", ref: "SOP-02",
    title: "Document the Lucky Method",
    status: "Writing",
    script: "The exact journey a client takes from first DM to paying customer. Written down for the first time.",
    notes: "The full customer journey map, written down so anyone on the team can run it.",
    scenes: ["Discovery", "Nurture", "Offer", "Close"],
    priority: "Normal",
    format: "Carousel",
    platform: "Instagram",
    tags: ["process", "client-journey"],
  },
  {
    id: "c-006", cat: "cat-site", ref: "WEB-01",
    title: "Rewrite the offers page",
    status: "Ready to Post",
    script: "Three offers. One clear next step each. That's it.",
    notes: "Three offers, one clear next step on each.",
    scenes: [],
    priority: "Normal",
    format: "Photo",
    platform: "Instagram",
    tags: ["website", "offers"],
  },
  {
    id: "c-007", cat: "cat-site", ref: "WEB-02",
    title: "Fix the link in bio destination",
    status: "Posted",
    script: "One link. One place. No menu of options.",
    notes: "One clear destination instead of a menu of options.",
    scenes: [],
    priority: "Normal",
    format: "Story",
    platform: "Instagram",
    tags: ["website", "cta"],
  },
  {
    id: "c-008", cat: "cat-clients", ref: "CLT-01",
    title: "Chase the outstanding proposal",
    status: "Inbox",
    script: "",
    notes: "Waiting on their side since last week. Follow up, then decide whether to close it out.",
    scenes: [],
    priority: "High",
    format: "Reel",
    platform: "Instagram",
    tags: ["proposal", "follow-up"],
  },
  {
    id: "c-009", cat: "cat-clients", ref: "CLT-02",
    title: "Monthly reporting for all clients",
    status: "Writing",
    script: "Numbers, what changed, what we're doing next month. One page per client.",
    notes: "Numbers, what we changed, what we are doing next month.",
    scenes: [],
    priority: "High",
    format: "Carousel",
    platform: "Instagram",
    tags: ["reporting", "clients"],
  },
  {
    id: "c-010", cat: "cat-engine", ref: "AGD-04",
    title: "Set up the freebie experiment tracking",
    status: "Ideas",
    script: "Three months of public numbers. What's working. What's not. No filter.",
    notes: "Three months of public numbers. Needs somewhere to record them each month.",
    scenes: [],
    priority: "Low",
    format: "Reel",
    platform: "Instagram",
    tags: ["experiment", "transparency"],
  },
];

export const SEED_FORMULAS = [
  {
    id: "f-001",
    name: "Value First",
    summary: "Lead with the insight, follow with the ask. Works best when the value is immediately obvious.",
    steps: [
      { label: "Hook", text: "One specific, surprising claim or result." },
      { label: "Proof", text: "Two or three lines that back it up concretely." },
      { label: "Bridge", text: "One sentence connecting the proof to the viewer's situation." },
      { label: "CTA", text: "Single, clear next action. No alternatives." },
    ],
  },
  {
    id: "f-002",
    name: "Permission-Based",
    summary: "Ask before telling. Reduces resistance by making the viewer feel in control.",
    steps: [
      { label: "Setup", text: "Name a problem the viewer recognizes." },
      { label: "Ask", text: "If you want X, here's what actually works." },
      { label: "Deliver", text: "Give it. All of it. No teasing." },
      { label: "CTA", text: "Soft ask — comment, save, or reply." },
    ],
  },
  {
    id: "f-003",
    name: "Contrast Hook",
    summary: "Before vs after. Then vs now. Most creators do X, the best do Y.",
    steps: [
      { label: "State A", text: "What most people do or believe." },
      { label: "State B", text: "What actually works (the flip)." },
      { label: "Reason", text: "Why the difference exists." },
      { label: "CTA", text: "Which side are you on? Comment or save." },
    ],
  },
  {
    id: "f-004",
    name: "Story Arc",
    summary: "Tension → Turn → Resolution. Classic narrative structure applied to short-form.",
    steps: [
      { label: "Tension", text: "Drop into the middle of the problem. No preamble." },
      { label: "Escalation", text: "Make it worse before it gets better." },
      { label: "Turn", text: "The insight or decision that changed everything." },
      { label: "Resolution", text: "The result. Specific numbers if possible." },
      { label: "CTA", text: "Save this. You'll want it when you're in the tension phase." },
    ],
  },
  {
    id: "f-005",
    name: "Number List",
    summary: "Numbered specificity creates trust. The number in the hook sets expectations.",
    steps: [
      { label: "Hook", text: "X things I wish I knew before [doing thing]." },
      { label: "List items", text: "Each point gets one sentence max. No fluff." },
      { label: "Kicker", text: "The one that surprises. Save it for last." },
      { label: "CTA", text: "Which one hit hardest? Reply below." },
    ],
  },
];

export const SEED_SERIES = [
  {
    id: "s-001",
    name: "Agency Diaries",
    cadence: "Weekly",
    what: "Behind-the-scenes of running a solo content agency. Real numbers, real decisions, no filter.",
    editing: "Cut tight. Under 60 seconds. Show the chaos, not the highlight reel.",
    hooks: "Week X of running an agency solo — here's what actually happened.",
    visuals: "Desk setup, screen recordings, raw footage. No studio lighting.",
    notes: "Post every Monday. This is the anchor content that everything else references.",
    links: [],
  },
  {
    id: "s-002",
    name: "CEO Decisions",
    cadence: "Bi-weekly",
    what: "Real business decisions with real numbers and real reasoning. One decision per episode.",
    editing: "Keep the pause before the answer. That's the hook. Don't cut it.",
    hooks: "I had to decide whether to [X]. Here's what I chose and why.",
    visuals: "Talking head, clean background. The story is in the words.",
    notes: "Goes live on Wednesdays. Pair with a longer breakdown in the caption.",
    links: [],
  },
  {
    id: "s-003",
    name: "Evergreen Triggers",
    cadence: "Monthly",
    what: "Comment-triggered content that delivers a lead magnet. One keyword, one resource.",
    editing: "Short and sharp. Under 30 seconds. The value is in what they get after commenting.",
    hooks: "Comment [KEYWORD] and I'll send you [RESOURCE].",
    visuals: "Screen showing the resource + quick demo of what's inside.",
    notes: "Each one needs the ManyChat flow live before posting. Never post without testing first.",
    links: [],
  },
];
